package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type StructInfo struct {
	Name   string
	Fields []FieldInfo
}

type FieldInfo struct {
	Name        string
	Type        string
	IsPointer   bool
	IsSlice     bool
	IsMap       bool
	IsStruct    bool
	IsPrimitive bool
	ElemType    string
	ResetCode   string
}

type PackageInfo struct {
	Name    string
	Dir     string
	Structs []StructInfo
}

const resetTemplate = `// Code generated by reset generator. DO NOT EDIT.
// source: reset generator

package {{.PackageName}}

{{range .Structs}}
// Reset сбрасывает состояние структуры {{.Name}} к начальным значениям
func (rs *{{.Name}}) Reset() {
	if rs == nil {
		return
	}

{{range .Fields}}
	{{.ResetCode}}
{{end}}
}
{{end}}
`

func main() {
	rootDir := findModuleRoot()
	if rootDir == "" {
		fmt.Fprintf(os.Stderr, "Error: cannot find module root\n")
		os.Exit(1)
	}

	fmt.Printf("Module root: %s\n", rootDir)

	packages, err := scanPackages(rootDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error scanning packages: %v\n", err)
		os.Exit(1)
	}

	for _, pkg := range packages {
		if len(pkg.Structs) == 0 {
			continue
		}

		if err := generateResetFile(pkg); err != nil {
			fmt.Fprintf(os.Stderr, "Error generating reset file for %s: %v\n", pkg.Name, err)
			os.Exit(1)
		}

		fmt.Printf("Generated reset.gen.go for package %s with %d struct(s)\n", pkg.Name, len(pkg.Structs))
	}
}

func findModuleRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		return ""
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

func scanPackages(rootDir string) ([]PackageInfo, error) {
	pkgMap := make(map[string]*PackageInfo)

	err := filepath.Walk(rootDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		if info.IsDir() {
			name := info.Name()
			if name == ".git" || name == "vendor" || name == ".tools" ||
				name == "node_modules" || strings.HasPrefix(name, ".") {
				return filepath.SkipDir
			}
			return nil
		}

		if !strings.HasSuffix(path, ".go") ||
			strings.HasSuffix(path, "_test.go") ||
			strings.HasSuffix(path, ".gen.go") {
			return nil
		}

		structs, err := parseFile(path)
		if err != nil {
			return fmt.Errorf("error parsing %s: %w", path, err)
		}

		if len(structs) == 0 {
			return nil
		}

		dir := filepath.Dir(path)
		pkgName := filepath.Base(dir)

		if _, ok := pkgMap[dir]; !ok {
			pkgMap[dir] = &PackageInfo{
				Name: pkgName,
				Dir:  dir,
			}
		}

		pkgMap[dir].Structs = append(pkgMap[dir].Structs, structs...)
		return nil
	})

	if err != nil {
		return nil, err
	}

	var packages []PackageInfo
	for _, pkg := range pkgMap {
		packages = append(packages, *pkg)
	}

	return packages, nil
}

func parseFile(filename string) ([]StructInfo, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	var structs []StructInfo

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}

		if !hasGenerateComment(genDecl.Doc) {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			structInfo := StructInfo{
				Name: typeSpec.Name.Name,
			}

			for _, field := range structType.Fields.List {
				if len(field.Names) == 0 {
					continue
				}

				fieldInfo := parseField(field)
				structInfo.Fields = append(structInfo.Fields, fieldInfo)
			}

			structs = append(structs, structInfo)
		}
	}

	return structs, nil
}

func hasGenerateComment(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, comment := range doc.List {
		if strings.Contains(comment.Text, "generate:reset") {
			return true
		}
	}
	return false
}

func parseField(field *ast.Field) FieldInfo {
	fieldInfo := FieldInfo{
		Name: field.Names[0].Name,
	}

	typeStr := typeToString(field.Type)
	fieldInfo.Type = typeStr

	switch t := field.Type.(type) {
	case *ast.Ident:
		if isPrimitive(t.Name) {
			fieldInfo.IsPrimitive = true
		} else {
			fieldInfo.IsStruct = true
		}

	case *ast.StarExpr:
		fieldInfo.IsPointer = true
		if ident, ok := t.X.(*ast.Ident); ok {
			fieldInfo.ElemType = ident.Name
		}

	case *ast.ArrayType:
		fieldInfo.IsSlice = true
		if ident, ok := t.Elt.(*ast.Ident); ok {
			fieldInfo.ElemType = ident.Name
		}

	case *ast.MapType:
		fieldInfo.IsMap = true
	}

	return fieldInfo
}

func typeToString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + typeToString(t.X)
	case *ast.ArrayType:
		return "[]" + typeToString(t.Elt)
	case *ast.MapType:
		return fmt.Sprintf("map[%s]%s", typeToString(t.Key), typeToString(t.Value))
	case *ast.SelectorExpr:
		return fmt.Sprintf("%s.%s", typeToString(t.X), t.Sel.Name)
	default:
		return fmt.Sprintf("%T", expr)
	}
}

func isPrimitive(typeName string) bool {
	primitives := map[string]bool{
		"int": true, "int8": true, "int16": true, "int32": true, "int64": true,
		"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true,
		"float32": true, "float64": true,
		"complex64": true, "complex128": true,
		"string": true, "bool": true,
		"byte": true, "rune": true,
	}
	return primitives[typeName]
}

func isInterfaceType(typeName string) bool {
	interfaces := map[string]bool{
		"error":       true,
		"interface{}": true,
		"any":         true,
	}
	return interfaces[typeName]
}

func generateResetFile(pkg PackageInfo) error {
	for i := range pkg.Structs {
		for j := range pkg.Structs[i].Fields {
			code := generateResetCode(pkg.Structs[i].Fields[j])
			pkg.Structs[i].Fields[j].ResetCode = code
		}
	}

	tmpl, err := template.New("reset").Parse(resetTemplate)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	data := struct {
		PackageName string
		Structs     []StructInfo
	}{
		PackageName: pkg.Name,
		Structs:     pkg.Structs,
	}

	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("error formatting: %w\nCode:\n%s", err, buf.String())
	}

	outputPath := filepath.Join(pkg.Dir, "reset.gen.go")
	return os.WriteFile(outputPath, formatted, 0644)
}

func generateResetCode(field FieldInfo) string {
	if field.IsSlice {
		return fmt.Sprintf("rs.%s = rs.%s[:0]", field.Name, field.Name)
	}

	if field.IsMap {
		return fmt.Sprintf("clear(rs.%s)", field.Name)
	}

	if field.IsPointer {
		if isPrimitive(field.ElemType) || isInterfaceType(field.ElemType) {
			return fmt.Sprintf(`if rs.%s != nil {
	*rs.%s = %s
}`, field.Name, field.Name, zeroValue(field.ElemType))
		}
		return fmt.Sprintf(`if rs.%s != nil {
	rs.%s.Reset()
}`, field.Name, field.Name)
	}

	if field.IsPrimitive {
		return fmt.Sprintf("rs.%s = %s", field.Name, zeroValue(field.Type))
	}

	if field.IsStruct {
		if isInterfaceType(field.Type) {
			return fmt.Sprintf("rs.%s = nil", field.Name)
		}
		return fmt.Sprintf(`if rs.%s != nil {
	rs.%s.Reset()
}`, field.Name, field.Name)
	}

	return fmt.Sprintf("// TODO: reset field %s of type %s", field.Name, field.Type)
}

func zeroValue(typeName string) string {
	switch typeName {
	case "string":
		return `""`
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64",
		"complex64", "complex128",
		"byte", "rune":
		return "0"
	case "bool":
		return "false"
	case "error", "interface{}", "any":
		return "nil"
	default:
		return "nil"
	}
}
