// Package main предоставляет утилиту для генерации методов Reset() для структур.
//
// Утилита сканирует все пакеты в проекте, находит структуры с комментарием
// // generate:reset и генерирует для них метод Reset(), который сбрасывает
// все поля структуры к нулевым значениям.
//
// Правила сброса:
//   - Примитивы (int, string, bool, float и т.д.) → нулевые значения
//   - Слайсы → обрезаются до нулевой длины (s = s[:0])
//   - Мапы → очищаются через clear()
//   - Указатели → сбрасываются значения по адресу
//   - Вложенные структуры с методом Reset() → вызывают Reset()
//
// Использование:
//
//	go run ./cmd/reset/
//	go generate ./...
//
// Для автоматической генерации добавьте в файл с типами:
//
//	//go:generate go run github.com/Eressleep/metrics-tpl/cmd/reset
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// StructInfo содержит информацию о структуре для генерации
type StructInfo struct {
	Name   string
	Fields []FieldInfo
}

// FieldInfo содержит информацию о поле структуры
type FieldInfo struct {
	Name        string
	Type        string
	IsPointer   bool
	IsSlice     bool
	IsMap       bool
	IsStruct    bool
	IsPrimitive bool
	ElemType    string // для указателей, слайсов, мапов
}

// PackageInfo содержит информацию о пакете
type PackageInfo struct {
	Name    string
	Dir     string
	Structs []StructInfo
}

const resetTemplate = `// Code generated by reset generator. DO NOT EDIT.
// source: reset generator

package {{.PackageName}}

{{range .Structs}}
// Reset сбрасывает состояние структуры {{.Name}} к начальным значениям
func (rs *{{.Name}}) Reset() {
	if rs == nil {
		return
	}

{{range .Fields}}
	{{.ResetCode}}
{{end}}
}
{{end}}
`

func main() {
	// Находим корневую директорию проекта (где находится go.mod)
	rootDir, err := findModuleRoot()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error finding module root: %v\n", err)
		os.Exit(1)
	}

	// Сканируем все пакеты
	packages, err := scanPackages(rootDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error scanning packages: %v\n", err)
		os.Exit(1)
	}

	// Генерируем файлы для каждого пакета
	for _, pkg := range packages {
		if len(pkg.Structs) == 0 {
			continue
		}

		if err := generateResetFile(pkg); err != nil {
			fmt.Fprintf(os.Stderr, "Error generating reset file for %s: %v\n", pkg.Name, err)
			os.Exit(1)
		}

		fmt.Printf("Generated reset.gen.go for package %s with %d struct(s)\n", pkg.Name, len(pkg.Structs))
	}
}

// findModuleRoot находит корневую директорию модуля (где go.mod)
func findModuleRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		return ""
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}

// scanPackages сканирует все пакеты в директории
func scanPackages(rootDir string) ([]PackageInfo, error) {
	var packages []PackageInfo
	pkgMap := make(map[string]*PackageInfo)

	err := filepath.Walk(rootDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		// Пропускаем директории, которые не должны сканироваться
		if info.IsDir() {
			name := info.Name()
			if name == ".git" || name == "vendor" || name == ".tools" ||
				name == "node_modules" || strings.HasPrefix(name, ".") {
				return filepath.SkipDir
			}
			return nil
		}

		// Обрабатываем только .go файлы (не сгенерированные и не тестовые)
		if !strings.HasSuffix(path, ".go") ||
			strings.HasSuffix(path, "_test.go") ||
			strings.HasSuffix(path, ".gen.go") {
			return nil
		}

		// Парсим файл
		structs, err := parseFile(path)
		if err != nil {
			return fmt.Errorf("error parsing %s: %w", path, err)
		}

		if len(structs) == 0 {
			return nil
		}

		// Определяем пакет
		dir := filepath.Dir(path)
		pkgName := filepath.Base(dir)

		if _, ok := pkgMap[dir]; !ok {
			pkgMap[dir] = &PackageInfo{
				Name: pkgName,
				Dir:  dir,
			}
		}

		pkgMap[dir].Structs = append(pkgMap[dir].Structs, structs...)

		return nil
	})

	if err != nil {
		return nil, err
	}

	for _, pkg := range pkgMap {
		packages = append(packages, *pkg)
	}

	return packages, nil
}

// parseFile парсит файл и находит структуры с комментарием // generate:reset
func parseFile(filename string) ([]StructInfo, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	var structs []StructInfo

	// Ищем структуры с комментарием // generate:reset
	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}

		// Проверяем комментарий
		if !hasGenerateComment(genDecl.Doc) {
			continue
		}

		for _, spec := range genDecl.Specs {
			typeSpec, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}

			structType, ok := typeSpec.Type.(*ast.StructType)
			if !ok {
				continue
			}

			structInfo := StructInfo{
				Name: typeSpec.Name.Name,
			}

			// Обрабатываем поля структуры
			for _, field := range structType.Fields.List {
				if len(field.Names) == 0 {
					continue // пропускаем встроенные поля
				}

				fieldInfo := parseField(field)
				structInfo.Fields = append(structInfo.Fields, fieldInfo)
			}

			structs = append(structs, structInfo)
		}
	}

	return structs, nil
}

// hasGenerateComment проверяет наличие комментария // generate:reset
func hasGenerateComment(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}

	for _, comment := range doc.List {
		if strings.Contains(comment.Text, "generate:reset") {
			return true
		}
	}

	return false
}

// parseField анализирует поле структуры
func parseField(field *ast.Field) FieldInfo {
	fieldInfo := FieldInfo{
		Name: field.Names[0].Name,
	}

	typeStr := typeToString(field.Type)
	fieldInfo.Type = typeStr

	switch t := field.Type.(type) {
	case *ast.Ident:
		// Примитивный тип или структура
		if isPrimitive(t.Name) {
			fieldInfo.IsPrimitive = true
		} else {
			fieldInfo.IsStruct = true
		}

	case *ast.StarExpr:
		// Указатель
		fieldInfo.IsPointer = true
		if ident, ok := t.X.(*ast.Ident); ok {
			fieldInfo.ElemType = ident.Name
		}

	case *ast.ArrayType:
		// Слайс
		fieldInfo.IsSlice = true
		if ident, ok := t.Elt.(*ast.Ident); ok {
			fieldInfo.ElemType = ident.Name
		}

	case *ast.MapType:
		// Мапа
		fieldInfo.IsMap = true
	}

	return fieldInfo
}

// typeToString преобразует AST-тип в строку
func typeToString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.StarExpr:
		return "*" + typeToString(t.X)
	case *ast.ArrayType:
		return "[]" + typeToString(t.Elt)
	case *ast.MapType:
		return fmt.Sprintf("map[%s]%s", typeToString(t.Key), typeToString(t.Value))
	case *ast.SelectorExpr:
		return fmt.Sprintf("%s.%s", typeToString(t.X), t.Sel.Name)
	default:
		return fmt.Sprintf("%T", expr)
	}
}

// isPrimitive проверяет, является ли тип примитивным
func isPrimitive(typeName string) bool {
	primitives := map[string]bool{
		"int": true, "int8": true, "int16": true, "int32": true, "int64": true,
		"uint": true, "uint8": true, "uint16": true, "uint32": true, "uint64": true,
		"float32": true, "float64": true,
		"complex64": true, "complex128": true,
		"string": true, "bool": true,
		"byte": true, "rune": true,
	}

	return primitives[typeName]
}

// generateResetFile генерирует файл reset.gen.go для пакета
func generateResetFile(pkg PackageInfo) error {
	// Добавляем код сброса для каждого поля
	for i := range pkg.Structs {
		for j := range pkg.Structs[i].Fields {
			code := generateResetCode(pkg.Structs[i].Fields[j])
			pkg.Structs[i].Fields[j].ResetCode = code
		}
	}

	// Генерируем файл по шаблону
	tmpl, err := template.New("reset").Parse(resetTemplate)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	data := struct {
		PackageName string
		Structs     []StructInfo
	}{
		PackageName: pkg.Name,
		Structs:     pkg.Structs,
	}

	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}

	// Форматируем код
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("error formatting generated code: %w\nGenerated code:\n%s", err, buf.String())
	}

	// Записываем файл
	outputPath := filepath.Join(pkg.Dir, "reset.gen.go")
	return os.WriteFile(outputPath, formatted, 0644)
}

// generateResetCode генерирует код сброса для поля
func generateResetCode(field FieldInfo) string {
	if field.IsSlice {
		return fmt.Sprintf("rs.%s = rs.%s[:0]", field.Name, field.Name)
	}

	if field.IsMap {
		return fmt.Sprintf("clear(rs.%s)", field.Name)
	}

	if field.IsPointer {
		return fmt.Sprintf(`if rs.%s != nil {
	*rs.%s = %s
}`, field.Name, field.Name, zeroValue(field.ElemType))
	}

	if field.IsPrimitive {
		return fmt.Sprintf("rs.%s = %s", field.Name, zeroValue(field.Type))
	}

	if field.IsStruct {
		return fmt.Sprintf(`if resetter, ok := interface{}(&rs.%s).(interface{ Reset() }); ok {
	resetter.Reset()
}`, field.Name)
	}

	return fmt.Sprintf("// TODO: reset field %s of type %s", field.Name, field.Type)
}

// zeroValue возвращает нулевое значение для типа
func zeroValue(typeName string) string {
	switch typeName {
	case "string":
		return `""`
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64",
		"complex64", "complex128",
		"byte", "rune":
		return "0"
	case "bool":
		return "false"
	default:
		return "nil"
	}
}
